-- PROD seed: Mèche Studio feed (mirrors the curated staging feed).
-- Run once in the PROD SQL editor after `supabase db push`. Safe to re-run.
delete from feed_items;
insert into feed_items (kind, name, tag, hair, mood, loves, descr, label, by, match, image_url) values
  ('studio', '{"en":"Caramel soft bob","fr":"Carré flou caramel"}'::jsonb, '{"en":"TRENDING","fr":"TENDANCE"}'::jsonb, 'bob', 'warm', '12.4k', '{"en":"Soft shoulder bob, caramel tones","fr":"Carré doux aux épaules, reflets caramel"}'::jsonb, '{"en":"MÈCHE STUDIO","fr":"STUDIO MÈCHE"}'::jsonb, '{"en":"Summer 26 edit","fr":"Édition Été 26"}'::jsonb, null, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=1100&fit=crop'),
  ('studio', '{"en":"Volume curls","fr":"Boucles volume"}'::jsonb, '{"en":"FOR YOU","fr":"POUR TOI"}'::jsonb, 'curly', 'night', '19.3k', '{"en":"Natural curls, big volume","fr":"Boucles naturelles, gros volume"}'::jsonb, '{"en":"MÈCHE STUDIO","fr":"STUDIO MÈCHE"}'::jsonb, '{"en":"Editorial reference","fr":"Référence éditoriale"}'::jsonb, null, 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&h=1100&fit=crop'),
  ('studio', '{"en":"Wavy blond lob","fr":"Lob blond ondulé"}'::jsonb, '{"en":"NEW","fr":"NOUVEAU"}'::jsonb, 'long', 'sand', '8.1k', '{"en":"Wavy mid-length, blond","fr":"Mi-long ondulé, reflets blond"}'::jsonb, '{"en":"MÈCHE STUDIO","fr":"STUDIO MÈCHE"}'::jsonb, '{"en":"Editorial reference","fr":"Référence éditoriale"}'::jsonb, null, 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=800&h=1100&fit=crop'),
  ('studio', '{"en":"Textured pixie","fr":"Pixie texturé"}'::jsonb, '{"en":"BOLD","fr":"OSÉ"}'::jsonb, 'pixie', 'cool', '4.7k', '{"en":"Very short, textured","fr":"Très court, ultra texturé"}'::jsonb, '{"en":"MÈCHE STUDIO","fr":"STUDIO MÈCHE"}'::jsonb, '{"en":"Editorial reference","fr":"Référence éditoriale"}'::jsonb, null, 'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=800&h=1100&fit=crop'),
  ('studio', '{"en":"Textured crop","fr":"Coupe courte texturée"}'::jsonb, '{"en":"CLASSIC","fr":"CLASSIQUE"}'::jsonb, 'short', 'cool', '6.0k', '{"en":"Clean fade, textured top","fr":"Dégradé net, texture au sommet"}'::jsonb, '{"en":"MÈCHE STUDIO","fr":"STUDIO MÈCHE"}'::jsonb, '{"en":"Editorial reference","fr":"Référence éditoriale"}'::jsonb, null, 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=800&h=1100&fit=crop');
