-- `web_studio` : l'interrupteur d'arrêt du tunnel payant web (web/src).
--
-- Aucun changement de schéma. Comme `min_version` (0032), on ajoute une clé à `app_config` (0027),
-- déjà lisible par tout le monde et déjà écrite au seul service_role (pas de policy d'insert = refus
-- par RLS, verrouillé par Postgres et pas par du code applicatif).
--
-- ── Le besoin : fermer le studio SANS toucher à Railway ─────────────────────────────────────────
-- Le même service Railway sert la landing, les pages légales ET le studio. Couper le service pour
-- suspendre le studio emporterait les pages légales, qui sont un engagement public opposable
-- (voir CLAUDE.md → « Legal pages are a contract with the code »). Et un redéploiement ne convient
-- pas non plus : les VITE_* sont inlinées au BUILD, donc passer par une variable Railway impose un
-- rebuild complet, soit plusieurs minutes pendant lesquelles on continue d'encaisser.
-- Ici, une ligne SQL suffit et l'effet est immédiat au prochain chargement de page :
--   update app_config set value = '0', updated_at = now() where key = 'web_studio';   -- fermé
--   update app_config set value = '1', updated_at = now() where key = 'web_studio';   -- ouvert
--
-- ── QUI lit cette clé : le SERVEUR, pas le navigateur ──────────────────────────────────────────
-- `web/server.js` la relit toutes les 30 s et, fermé, ne sert plus RIEN sous /studio : ni le shell
-- HTML, ni les assets. La réponse est un 503 `no-store`.
--
-- Ce choix est le coeur du mécanisme. Une garde équivalente dans le bundle React se désactiverait
-- depuis les devtools en deux clics, et ne serait de toute façon pas relue par un onglet déjà
-- ouvert. Ici le bundle n'est pas envoyé : il n'y a rien à réactiver côté client. C'est la
-- différence entre « l'interface refuse » et « le studio n'existe plus ».
--
-- Conséquence à connaître : un onglet DÉJÀ chargé garde son JavaScript et peut continuer à parler à
-- Supabase jusqu'à ce qu'il recharge. La fermeture arrête l'ARRIVÉE de nouveaux visiteurs, elle ne
-- tue pas les sessions en cours, et c'est voulu : quelqu'un qui vient de payer doit pouvoir
-- récupérer son image. `resumableGeneration` tient 24 h sur un aperçu verrouillé, donc un acheteur
-- peut revenir bien après la fermeture. L'interrupteur ne doit jamais transformer une panne en vol.
--
-- ── FAIL OPEN, comme min_version ───────────────────────────────────────────────────────────────
-- Clé absente, valeur vide, variables d'env manquantes, Supabase injoignable : le studio reste
-- OUVERT (et le serveur conserve la dernière valeur connue). Une panne réseau ne doit jamais être
-- indiscernable d'une fermeture volontaire, sinon Supabase qui tousse ferme la boutique tout seul,
-- exactement quand on a le moins besoin d'une surprise. Ne jamais inverser ce défaut.
--
-- Ce n'est pas pour autant un contrôle de sécurité, et il ne remplace RIEN côté données : les
-- garanties restent `generate` qui réserve le crédit avant l'appel payant (0030) et `unlock` qui
-- débite avant de révéler (0026). C'est un levier d'exploitation, pour couper l'hémorragie si
-- Paddle déraille, si le coût s'emballe ou si un bug livre mal.
--
-- ── Portée : le WEB uniquement ─────────────────────────────────────────────────────────────────
-- Cette clé n'est lue que par web/src. Elle ne coupe pas l'app : `locked_first_try` est
-- l'interrupteur de l'app, et les deux sont indépendants exprès. Fermer le web ne doit pas changer
-- l'expérience de quelqu'un sur iOS.
insert into app_config (key, value) values ('web_studio', '1')
  on conflict (key) do nothing;
